typography_spectrum: 0.18410080019384623
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.08463381533510983
  lightness: 0.4084232032764703
  saturation: 0.02282790536992252
  rhythmicContrast: 0.23436179826967418
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.75624
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Magdalena
  email: magdalena@malpainteractive.com
name: Malpa Interactive
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Inbound Marketing Company
purpose: []
